GraphMultiEpg.py: Create time tuple
File "/usr/lib/enigma2/python/Tools/Import.py", line 2, in my_import
    mod = __import__(name)
  File "/usr/lib/enigma2/python/Plugins/Extensions/GraphMultiEPG/plugin.py", line 2, in <module>
    from Plugins.Extensions.GraphMultiEPG.GraphMultiEpg import GraphMultiEPG
  File "/usr/lib/enigma2/python/Plugins/Extensions/GraphMultiEPG/GraphMultiEpg.py", line 48, in <module>
    config.misc.graph_mepg.prime_time = ConfigClock(default=mktime(now_time))
TypeError: Tuple or struct_time argument required