NimManager: Solve GSOD when switching to combi DVB-S + DVB-T2/C mode
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 69, in action
    return ActionMap.action(self, contexts, action)
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 49, in action
    res = self.actions[action]()
  File "/usr/lib/enigma2/python/Screens/Satconfig.py", line 631, in keyRight
    ConfigListScreen.keyRight(self)
  File "/usr/lib/enigma2/python/Components/ConfigList.py", line 227, in keyRight
    self["config"].handleKey(KEY_RIGHT)
  File "/usr/lib/enigma2/python/Components/ConfigList.py", line 41, in handleKey
    selection[1].handleKey(key)
  File "/usr/lib/enigma2/python/Components/config.py", line 347, in handleKey
    self.value = self.choices[(i + 1) % nchoices]
  File "/usr/lib/enigma2/python/Components/config.py", line 318, in setValue
    self.changed()
  File "/usr/lib/enigma2/python/Components/config.py", line 109, in changed
    x(self)
  File "/usr/lib/enigma2/python/Tools/BoundFunction.py", line 9, in __call__
    return self.fnc(*self.args + args, **newkwargs)
  File "/usr/lib/enigma2/python/Components/NimManager.py", line 1495, in tunerTypeChanged
    tunerTypeChanged(nimmgr, configElement.value[-1], initial)
  File "/usr/lib/enigma2/python/Components/NimManager.py", line 1488, in tunerTypeChanged
    fe_id = configElement.fe_id
AttributeError: 'str' object has no attribute 'fe_id'