NimManager - fix crash getFriendlyFullDescriptionCompressed introduced in https://github.com/OpenPLi/enigma2/commit/7de73064e866d59467794e6142eacf127a0481fa
NameError: global name 'getFriendlyFullDescription' is not defined