Task.py: Decode data to unicode
execute: 0 mkfs.ext4 -T largefile -N 262144 -m0 -O dir_index,sparse_super /dev/sda1
[Mkfs] b'mke2fs 1.46.1 (9-Feb-2021)\n'
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/Task.py", line 209, in processStderr
    self.processOutput(data)
  File "/usr/lib/enigma2/python/Components/Harddisk.py", line 906, in processOutput
    if 'Writing inode tables:' in data:
TypeError: a bytes-like object is required, not 'str'