GraphMultiEpg: use tuple to mktime instead of list
It should fix the following error:

Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 58, in action
    res = self.actions[action]()
  File "/usr/lib/enigma2/python/Plugins/Extensions/GraphMultiEPG/GraphMultiEpg.py", line 1083, in togglePrimeNow
    self.setNewTime("prime_time")
  File "/usr/lib/enigma2/python/Plugins/Extensions/GraphMultiEPG/GraphMultiEpg.py", line 1115, in setNewTime
    date = mktime([now[0], now[1], now[2], prime[0], prime[1], 0, 0, 0, now[8]])
TypeError: Tuple or struct_time argument required