TimerEdit: check eit for None value before calling lookupEventId
This commit will ensure that eit is not None before calling lookupEventId.
Same check exists here: https://github.com/OpenPLi/enigma2/blob/19151ea6b193f1c0703d21d45b63bdfc03391171/lib/python/Screens/TimerEntry.py#L472

Without above check most probably we are getting the following error:
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 77, in action
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 57, in action
  File "/usr/lib/enigma2/python/Screens/Menu.py", line 56, in okbuttonClick
  File "/usr/lib/enigma2/python/Tools/BoundFunction.py", line 9, in __call__
  File "/usr/lib/enigma2/python/Screens/Menu.py", line 69, in runScreen
  File "/usr/lib/enigma2/python/Screens/Menu.py", line 75, in openDialog
  File "/usr/lib/enigma2/python/mytest.py", line 289, in openWithCallback
    dlg = self.open(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 299, in open
    dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 242, in instantiateDialog
    return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
  File "/usr/lib/enigma2/python/mytest.py", line 266, in doInstantiateDialog
    dlg.applySkin()
  File "/usr/lib/enigma2/python/Components/GUISkin.py", line 154, in applySkin
  File "/usr/lib/enigma2/python/Components/GUISkin.py", line 57, in createGUIScreen
  File "/usr/lib/enigma2/python/Screens/TimerEdit.py", line 258, in fillTimerList
  File "/usr/lib/enigma2/python/Screens/TimerEdit.py", line 167, in updateState
TypeError: in method 'eEPGCache_lookupEventId', argument 3 of type 'int'

Issue introduced on 624099ec5fd5d55a5f9f2eef9b8397f44314d8cd.