t2mi: add missing parenthesis in t2mi_plp_id
It should fix the following error:
File "/usr/lib/enigma2/python/Screens/ScanSetup.py", line 1281, in addSatTransponder
TypeError: unsupported operand type(s) for +: 'int' and 'str'