Fixes " Add HW-descrambler slot reset workaround" (#4387)
* Reapply "[SoftCSA] Add HW-descrambler slot reset workaround"

This reverts commit 10c456bbf1852d3701e9baaaed3017b7d7b59414.

* [softcsa] Fix build part 1

Use getConfigIntValue() instead.

* [descrambler.h] Revert data type argument descrambler_init() back to integer

Revert:
https://github.com/Hains/enigma2/commit/0017647825bcb4e656b0b99b660b69634c83635e#diff-0d41511784e9dc1f889abf397e9f0fafeb1dc55c5bd86147caa489bfcb8d1e7dL6

 ../../sources/enigma2-3.14+git/lib/dvb_ci/dvbci_ccmgr.cpp:801:70: error: invalid conversion from 'int' to 'eDVBCISlot*' [-fpermissive]
|   801 |                 m_descrambler_fd = descrambler_init(m_slot->getSlotID(), m_slot->getCADemuxID() + (m_slot->getIsCA0Excluded() ? 1 : 0));
|       |                                                     ~~~~~~~~~~~~~~~~~^~
|       |                                                                      |
|       |                                                                      int

* [servicedvb.cpp] Reinstate updateAudioCache()

We still have calls to updateAudioCache().
Add the function back along with resetHwDescramblerSlot().

Fix:
| /usr/src/debug/enigma2/3.14+git/lib/service/servicedvb.h:154:(.text+0x18cf4): undefined reference to `eDVBServicePlay::updateAudioCache(int, int)'