UsageConfig.py: Cast map() to list
map() returns iterator instead of list with Python 3.

File "/usr/lib/enigma2/python/Components/config.py", line 337, in setChoices
    self.choices = choicesList(choices)
  File "/usr/lib/enigma2/python/Components/config.py", line 193, in __init__
    assert False, "choices must be dict or list!"
AssertionError: choices must be dict or list!