StbHardware.py: long() is deprecated and merged with int
File "/usr/lib/enigma2/python/Tools/StbHardware.py", line 11, in getFPVersion
    ret = long(open("/proc/stb/fp/version", "r").read())
NameError: name 'long' is not defined