FlashImage: Solve GSOD when downloading json image list fails
Sorry that I forgot to change the url printing in the except. During
testing all the feeds I testing were working. Yesterday in the late
evening the feed from Open Vision had some temporary issues

[eDVBPESReader] ERROR reading PES (fd=87): Value too large for defined data type
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Screens/FlashImage.py", line 115, in getImagesList
    self.jsonlist = dict(json.load(urlopen(self.selectedImage[1]["url"], timeout=3)))
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
  File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
  File "/usr/lib/python3.9/urllib/request.py", line 1350, in do_open
  File "/usr/lib/python3.9/http/client.py", line 1377, in getresponse
  File "/usr/lib/python3.9/http/client.py", line 320, in begin
  File "/usr/lib/python3.9/http/client.py", line 281, in _read_status
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Screens/FlashImage.py", line 117, in getImagesList
    print("[FlashImage] getImagesList Error: Unable to load json data from URL '%s'!" % self.selectedImage["url"])
TypeError: tuple indices must be integers or slices, not str
[ePyObject] (CallObject(<bound method SelectImage.getImagesList of <class 'Screens.FlashImage.SelectImage'>>,()) failed)