Menu.py: exec is a method now
File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 55, in <module>
    from Screens.Menu import MainMenu, mdom
  File "/usr/lib/enigma2/python/Screens/Menu.py", line 65
    exec text
         ^
SyntaxError: Missing parentheses in call to 'exec'