enigma2.sh: define missing LC_ALL
Starting Enigma2 from enigma2.sh (init 3) causes the following errors:

  File "/usr/lib/enigma2/python/RecordTimer.py", line 424, in activate
    open(self.Filename + self.record_service.getFilenameExtension(), "w").close()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 41-48: ordinal not in range(128)

Starting Enigma2 from console using init 4 && enigma2 causes no error!

Long story, short, sys.getfilesystemencoding() returns ascii when using init 3 (via enigma2.sh).
That happens because the environment doesn't contain the LC_ALL or LC_CTYPE environment variables.

environ({'ENIGMA_DEBUG_LVL': '3', 'LD_PRELOAD': '/usr/lib/libopen.so.0.0.0', 'SHELL': '/bin/sh', 'RUNLEVEL': '3', 'PWD': '/home/root', 'HOME': '/home/root', 'TERM': 'linux', 'INIT_VERSION': 'sysvinit-2.99', 'SHLVL': '1', 'CONSOLE': '/dev/console', 'PREVLEVEL': 'N', 'PATH': '/sbin:/usr/sbin:/bin:/usr/bin', 'OLDPWD': '/', '_': '/usr/bin/enigma2', 'prefix': '/usr', 'exec_prefix': '/usr', 'bindir': '/usr/bin', 'sbindir': '/usr/sbin', 'libexecdir': '/usr/libexec', 'datarootdir': '/usr/share', 'datadir': '/usr/share', 'sysconfdir': '/etc', 'sharedstatedir': '/com', 'localstatedir': '/var', 'libdir': '/usr/lib', 'localedir': '/usr/share/locale', 'PYTHONPATH': '/usr/lib/enigma2/python'})

The fix, set a default LC_ALL to en_GB.utf8 just like we are doing on /etc/profile.d/utf8.sh

That makes the sys.getfilesystemencoding() to make use of utf-8 without changing code everywhere in enigma2.

Obviously explicit is better than implicit, if you are feeling using crazy LC_ALL values, add encoding='utf8'
to open function in order to stop it from crashing with unicode files.