estring: Fix build
c is unsigned char, so no need to check for greater than zero or equal to zero.

/../git/lib/base/estring.cpp:921:26: error: comparison is always true due to limited range of data type [-Werror=type-limits]
| 921 | if (0x00 <= c && c <= 0x7f) {