Solve possible GSOD introduced in 99da61ca
Thanks rantanplan for reporting

Traceback (most recent call last):
  File "/usr/lib/enigma2/python/mytest.py", line 545, in <module>
      Components.AVSwitch.InitAVSwitch()
  File "/usr/lib/enigma2/python/Components/AVSwitch.py", line 287, in InitAVSwitch
    config.av.hdmi_audio_source.addNotifier(setHDMIAudioSource)
  File "/usr/lib/enigma2/python/Components/config.py", line 131, in addNotifier
    notifier(self)
  File "/usr/lib/enigma2/python/Components/AVSwitch.py", line 285, in setHDMIAudioSource
    open(SystemInfo["HDMIAudioSource"], "w").write(configElement.value)
TypeError: coercing to Unicode: need string or buffer, bool found