Netlink.py: Use byte string to split
File "/usr/lib/enigma2/python/Components/InputHotplug.py", line 17, in doRead
    for event in self.nls.parse():
  File "/usr/lib/enigma2/python/Components/Netlink.py", line 17, in parse
    for item in data.split('\x00'):
builtins.TypeError: a bytes-like object is required, not 'str'