skin.py: Don't encode value to bytes
File "/usr/lib/enigma2/python/skin.py", line 428, in collectAttributes
    pos, size = context.parse(pos, size, font)
  File "/usr/lib/enigma2/python/skin.py", line 1021, in parse
    w, h = size.split(",")
TypeError: a bytes-like object is required, not 'str'