eerror: Make logging of timestamps optional
Define ENIGMA_DEBUG_TIME=1 in environment to enable timestamps in log.
Removed mysterious "#if 1" from enigma.cpp
Improve text to display environment variable name, so it's clear what the
environment name is.